# Data paths
data:
  csv_file: 'data/metadata.csv'
  image_dir: 'data/faces_224/'

# Model parameters
model:
  input_shape: [224, 224, 3]
  batch_size: 4
  epochs: 10
  dense_units: 128
  dropout_rate: 0.5
  learning_rate: 0.0001

# Training parameters
train:
  test_size: 0.2
  random_state: 42

# Paths for saving
save:
  model_path: 'models/xception_model.keras'
  log_path: 'logs/training_log.csv'

# Evaluation parameters
evaluate:
  threshold: 0.5
